steps:
  - label: ":julia: Julia {{matrix.julia}} + CUDA GPU"
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.julia}}"
      - JuliaCI/julia-test#v1:
          test_args: "--quickfail"
      - JuliaCI/julia-coverage#v1:
          codecov: true
    agents:
      queue: "juliagpu"
      cuda: "*"
    env:
      BACKEND_GROUP: "CUDA"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 60
    matrix:
      setup:
        julia:
          - "1"

  # - label: ":julia: Julia: {{matrix.julia}} + AMD GPU"
  #   plugins:
  #     - JuliaCI/julia#v1:
  #         version: "{{matrix.julia}}"
  #     - JuliaCI/julia-test#v1:
  #         test_args: "--quickfail"
  #     - JuliaCI/julia-coverage#v1:
  #         codecov: true
  #   env:
  #     JULIA_AMDGPU_CORE_MUST_LOAD: "1"
  #     JULIA_AMDGPU_HIP_MUST_LOAD: "1"
  #     JULIA_AMDGPU_DISABLE_ARTIFACTS: "1"
  #     BACKEND_GROUP: "AMDGPU"
  #   agents:
  #     queue: "juliagpu"
  #     rocm: "*"
  #     rocmgpu: "*"
  #   if: build.message !~ /\[skip tests\]/
  #   timeout_in_minutes: 60
  #   matrix:
  #     setup:
  #       julia:
  #         - "1"

env:
  RETESTITEMS_NWORKERS: 4
  RETESTITEMS_NWORKER_THREADS: 2
  SECRET_CODECOV_TOKEN: "vn5M+4wSwUFje6fl6UB/Q/rTmLHu3OlCCMgoPOXPQHYpLZTLz2hOHsV44MadAnxw8MsNVxLKZlXBKqP3IydU9gUfV7QUBtnvbUmIvgUHbr+r0bVaIVVhw6cnd0s8/b+561nU483eRJd35bjYDOlO+V5eDxkbdh/0bzLefXNXy5+ALxsBYzsp75Sx/9nuREfRqWwU6S45mne2ZlwCDpZlFvBDXQ2ICKYXpA45MpxhW9RuqfpQdi6sSR6I/HdHkV2cuJO99dqqh8xfUy6vWPC/+HUVrn9ETsrXtayX1MX3McKj869htGICpR8vqd311HTONYVprH2AN1bJqr5MOIZ8Xg==;U2FsdGVkX1+W55pTI7zq+NwYrbK6Cgqe+Gp8wMCmXY+W10aXTB0bS6zshiDYSQ1Y3piT91xFyNhS+9AsajY0yQ=="
