[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
torch = "^2.4.0"
deepxde = "^1.12.0"
neuraloperator = "^0.3.0"
wandb = "^0.17.5"
ipython = "^8.26.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
